export const REMOVE_EVENT = "REMOVE_EVENT";
export const SET_CURRENT_EVENT = "SET_CURRENT_EVENT";
export const ADD_EVENT = "ADD_EVENT";
export const GET_EVENTS = "GET_EVENTS"

export const ADD_REOCCURING = "ADD_REOCCURING";
export const REMOVE_REOCCURING = "REMOVE_REOCCURING";
export const GET_REOCCURING = "GET_REOCCURING"